name: Java CI

on:
  push:
    branches:
      - Benjaphol

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Compile Java
        run: |
          cd Benjaphol/HolidayTravelVehicles
          javac -d . *.java

      - name: Run main class
        run: |
          cd Benjaphol/HolidayTravelVehicles
          # If your main class is in a package, specify the full package path, e.g., java com.example.Main
          java Main
